apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: v1beta1-zoned-cluster
  namespace: pindakaas
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.52.100.0/12"]
    pods:
      cidrBlocks: ["192.101.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.23.8+vmware.2-tkg.2-zshippable
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: node-pool
          name: worker-pool-1
          replicas: 3
          failureDomain: tonychocoloney
        - class: node-pool
          name: worker-pool-2
          replicas: 3
          failureDomain: stroopwaffels
        - class: node-pool
          name: worker-pool-3
          replicas: 3
          failureDomain: pindas
    variables:
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: pindakaas-storagepolicy
